CREATE DATABASE IF NOT EXISTS investpilot;
USE investpilot;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS search_history (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NULL,
  query VARCHAR(255) NOT NULL,
  symbol VARCHAR(50) NOT NULL,
  company_name VARCHAR(255) NOT NULL,
  recommendation VARCHAR(50) NOT NULL,
  confidence INT NOT NULL,
  summary TEXT,
  result_json JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);
